# app/services/query_service.py
import re

from app.services.intent_classifier import classify_intent
from app.services.rule_engine import apply_rules
from app.services.rag_retriever import retrieve_context
from app.services.prompt_builder import build_prompt
from app.services.llm_client import call_llm  # HF API call
# Remove call_cloud_llm if not using separate cloud fallback
from app.services.confidence_checker import check_confidence
from app.services.sql_validator import validate_sql
from app.services.sql_executor import execute_safe_query
from app.services.formatter import format_answer, format_sql_results
from app.config import DB_TABLE
from app.utils.logger import get_logger

logger = get_logger(__name__)


def _extract_sql(llm_output: str) -> str:
    if not llm_output:
        return ""

    text = llm_output.strip()

    fence_match = re.search(r"```(?:sql)?\s*(.*?)```", text, flags=re.IGNORECASE | re.DOTALL)
    if fence_match:
        text = fence_match.group(1).strip()

    select_match = re.search(r"(select\b.*?)(?:;|$)", text, flags=re.IGNORECASE | re.DOTALL)
    if select_match:
        sql = select_match.group(1).strip()
        return f"{sql};"

    return text


def _is_greeting(text: str) -> bool:
    normalized = " ".join((text or "").lower().strip().split())
    greetings = {
        "hi",
        "hii",
        "hiii",
        "hello",
        "hey",
        "good morning",
        "good afternoon",
        "good evening",
    }
    return normalized in greetings

def handle_query(user_question: str):
    if not user_question or not user_question.strip():
        raise ValueError("Question cannot be empty.")

    logger.info("Starting query pipeline")

    if _is_greeting(user_question):
        logger.info("Greeting detected, returning conversational response")
        return "Hi! How can I help you today?", 1.0

    # Step 1: Intent (kept for logging/rules)
    intent = classify_intent(user_question)
    logger.info("Intent detected: %s", intent)
    refined_question = apply_rules(user_question, intent)

    # Step 2: Context / RAG
    context = retrieve_context(refined_question)
    logger.info("Context retrieved")

    # Step 3: SQL-first mode (always try DB execution first)
    sql_prompt = build_prompt(refined_question, context, "sql")
    sql_llm_response = call_llm(sql_prompt)
    sql_query = _extract_sql(sql_llm_response)
    logger.info("SQL candidate generated")

    if not validate_sql(sql_query):
        logger.warning("First SQL candidate failed validation; retrying SQL generation once")
        retry_prompt = (
            f"{sql_prompt}\n"
            "Important:\n"
            f"- Use only one table: {DB_TABLE}\n"
            "- Return exactly one valid SELECT query and nothing else.\n"
        )
        retry_sql_response = call_llm(retry_prompt)
        sql_query = _extract_sql(retry_sql_response)
        logger.info("Retry SQL candidate generated")

    if validate_sql(sql_query):
        logger.info("SQL validated successfully")
        results = execute_safe_query(sql_query)
        if isinstance(results, str):
            # DB/runtime error text from executor
            answer = results
            confidence = 0.0
        else:
            answer = format_sql_results(results, user_question)
            confidence = 1.0
    else:
        # Step 4: Fallback to general answer if SQL generation fails
        logger.warning("SQL generation/validation failed; falling back to general answer.")
        general_prompt = build_prompt(refined_question, context, "general")
        llm_response = call_llm(general_prompt)
        confidence = check_confidence(llm_response, context)
        answer = llm_response

    # Step 5: Format final answer
    answer = format_answer(answer)

    if not answer:
        raise RuntimeError("No answer generated by the pipeline.")

    logger.info("Query pipeline completed")
    return answer, confidence
