# AI_Knowledge_Assistant/app/services/sql_validator.py
"""
Validation logic to ensure generated SQL queries are safe and read-only.
Powered by sqlglot for semantic AST parsing and injection prevention.
"""
import sqlglot
from sqlglot import exp
from sqlglot.errors import ParseError
from app.config import DB_TABLE
from app.utils.logger import get_logger

logger = get_logger(__name__)

def validate_sql(sql_query: str) -> bool:
    """
    Validate SQL query to ensure it is a safe, read-only SELECT statement
    targeting only the allowed table, using Abstract Syntax Tree (AST) parsing.

    Args:
        sql_query (str): The SQL query generated by LLM.

    Returns:
        bool: True if valid and safe, False otherwise.
    """
    if not sql_query or not sql_query.strip():
        return False

    try:
        # 1. Parse the query into an AST using the MySQL dialect.
        # We use `parse` (returns a list) to easily detect stacked queries.
        statements = sqlglot.parse(sql_query, read="mysql")
        
        # Filter out empty statements (caused by safe trailing semicolons or comments)
        statements = [stmt for stmt in statements if stmt is not None]

        # 2. Block stacked queries (SQL Injection prevention)
        if len(statements) != 1:
            logger.warning("SQL rejected: Multiple statements detected. Possible injection attempt.")
            return False
        
        ast = statements[0]

        # 3. Ensure the root operation is strictly a SELECT
        if not isinstance(ast, exp.Select):
            logger.warning(
                "SQL rejected: Root operation is not a SELECT. Found: %s", 
                type(ast).__name__
            )
            return False

        # 4. Deep search for forbidden operations buried in subqueries or CTEs.
        # This prevents trickery like: SELECT * FROM (UPDATE users SET... RETURNING *)
        forbidden_classes = (
            exp.Insert, exp.Update, exp.Delete, exp.Drop, 
            exp.Alter, exp.Command, exp.Commit, exp.Rollback,
            exp.Create
        )
        for forbidden in forbidden_classes:
            if list(ast.find_all(forbidden)):
                logger.warning(
                    "SQL rejected: Contains forbidden nested operation: %s", 
                    forbidden.__name__
                )
                return False

        # 5. Extract and validate all referenced tables semantically
        referenced_tables = set()
        for table in ast.find_all(exp.Table):
            # table.name automatically strips backticks, quotes, and handles aliases safely
            if table.name:
                referenced_tables.add(table.name.lower())

        if not referenced_tables:
            logger.warning("SQL rejected: No table references found in the query.")
            return False

        allowed_table = DB_TABLE.lower()
        if referenced_tables != {allowed_table}:
            logger.warning(
                "SQL rejected: Table scope mismatch. referenced=%s allowed=%s",
                referenced_tables,
                allowed_table
            )
            return False

        logger.debug("SQL query validated successfully via AST.")
        return True

    except ParseError as e:
        # The LLM hallucinated invalid SQL syntax that cannot be executed anyway
        logger.warning("SQL rejected: Failed to parse query syntactically. Error: %s", str(e))
        return False
    except Exception as e:
        # Failsafe for unexpected errors
        logger.error("SQL rejected: Unexpected validation error: %s", str(e))
        return False