import re
from app.config import DB_TABLE
from app.utils.logger import get_logger

# Allowed SQL operations (read-only)
ALLOWED_OPERATIONS = ["select"]
logger = get_logger(__name__)

def validate_sql(sql_query: str) -> bool:
    """
    Validate SQL query to ensure it only contains allowed operations.

    Args:
        sql_query (str): The SQL query generated by LLM.

    Returns:
        bool: True if valid and safe, False otherwise.
    """
    # Normalize query
    query = sql_query.strip().lower()

    # Check for forbidden operations
    forbidden_keywords = ["insert", "update", "delete", "drop", "truncate", "alter", ";"]
    for keyword in forbidden_keywords:
        # Allow semicolon only at the end
        if keyword != ";" and keyword in query:
            logger.warning("SQL rejected due to forbidden keyword: %s", keyword)
            return False

    # Ensure it starts with allowed operations
    if not any(query.startswith(op) for op in ALLOWED_OPERATIONS):
        logger.warning("SQL rejected: not starting with allowed operation")
        return False

    # Allow only the configured table
    table_pattern = re.compile(r"\b(?:from|join)\s+`?([a-zA-Z0-9_]+)`?\b")
    referenced_tables = {match.group(1).lower() for match in table_pattern.finditer(query)}

    if not referenced_tables:
        logger.warning("SQL rejected: no table references found")
        return False

    allowed_table = DB_TABLE.lower()
    if referenced_tables != {allowed_table}:
        logger.warning("SQL rejected: table scope mismatch. referenced=%s allowed=%s", referenced_tables, allowed_table)
        return False

    logger.debug("SQL query validated successfully")
    return True
